### ISSUE TITLE
한가지 제안과 버그

### ISSUE THREAD

**Issue by letakkak32** [muno9748/HangulPatcher#10]
한글 입력이 켜져 있을 때 채팅창을 끄고 다시 켜면 한글 입력이 자동으로 켜지게 되었으면 좋겠네요.
(기존에는 채팅창을 끄면 영어로 설정됨. 다시 채팅창을 켜도 영어로 설정됨)

그리고 버그인데
모음이나 받침을 빽스페이스로 지울려고 할 때 전 글자가 지워지는 것이에요.
ㅇ->ㅏ(아)->ㄴ(안)->ㄴ(안ㄴ)->ㅑ(오타)(안냐)->backspace(냐) 이런식으로

**Comment by muno9748** [comment]
추후 3.0 버전에서 수정 예정.
