### ISSUE TITLE
윈도우11 실행버그

### ISSUE THREAD

**Issue by ImPhoto** [muno9748/HangulPatcher#11]
![Error 2021-10-29 오후 5_39_28](https://user-images.githubusercontent.com/93375091/139405031-f44e9ce1-3024-4a40-adc8-567ab569f8db.png)
이렇게 뜨면서 안되는데요
제 컴 이상인가요

**Comment by Amicabl** [comment]
저도 똑같은 문제를 겪고 있어요. 예전 버전을 다운받는 것까지 다 고쳐보려고 노력했어요

**Comment by image1212** [comment]
저도 윈11인데 잘되는거 보면 윈11 오류는 아닌것같네요

**Comment by muno9748** [comment]
3.0 버전에서 코드 리팩토링 및 수정 예정.
