### ISSUE TITLE
가끔씩 앱이 안꺼집니다

### ISSUE THREAD

**Issue by heoddakji** [muno9748/HangulPatcher#16]
가끔 앱이 안꺼지고 응답없음이 뜹니다. 고쳐주시면 감사하겠습니다.

**Comment by muno9748** [comment]
해당 문제는 3.0.3 버전에서 해결되었습니다.

**Comment by muno9748** [comment]
~~해당 버그는 3.0.5 버전에서 수정되었습니다. 감사합니다.~~
버그 재확인됨.

**Comment by muno9748** [comment]
3.0.6에서 최종적으로 수정되었습니다.
