### ISSUE TITLE
오버레이 딜레이

### ISSUE THREAD

**Issue by soshimee** [muno9748/HangulPatcher#17]
오버레이를 켰을때 딜레이가 약간 생깁니다.

**Comment by muno9748** [comment]
죄송하지만 해당 정보만으로는 문제를 수집하기 어렵습니다.
오버레이를 켰을때 딜레이라는것이 FPS 드롭인지, 아니면 지속적인 렉인지와 같은
상세한 정보를 알려주시면 감사하겠습니다.

**Comment by soshimee** [comment]
모두 아니고 입력 딜레이입니다. PvP를 할때 특히 많이 느껴집니다.

**Comment by muno9748** [comment]
키보드 키의 입력이 지연되는 것이라면, 오버레이는 그저 화면만 띄우기에 오버레이의 문제로 보기는 어려울 것 같습니다.
현재로서는 문제를 확인하기 어렵고, 속도 개선 방안이 없어 일단 보류하겠습니다. 감사합니다.

**Comment by soshimee** [comment]
더 추가하자면 전체화면이 아닐때 느껴지는 딜레이와 유사합니다. 전체화면에 오버레이를 킨 상태로 들어가게 되면 오버레이를 끈 상태와 전체화면 시작 느낌이 약간 다른것도 있습니다.

**Comment by muno9748** [comment]
오버레이를 켰을때, 전체화면 느낌이 다른 이유는 프로그램이 마인크래프트 창 위에 분리된 오버레이를 따로 만들어야 하는데,
마인크래프트가 전체화면 모드로 화면을 독점하면 그게 불가능해 프로그램에서 전체화면 기능을 통제하고 새로 구현했기 때문입니다.

오버레이 최적화 문제로 FPS 드롭이 일어났다면 최적화를 좀 더 세게 해볼 수 있겠으나, 입력 지연 현상은 문제 식별이 어려운 점 양해 부탁드립니다.
