### ISSUE TITLE
건의

### ISSUE THREAD

**Issue by Mqrry** [muno9748/HangulPatcher#4]
마인크래프트 폴더 내에서 options.txt 파일 내의 key_key.chat 의 값을 읽어서 챗오픈 키를 설정하게 하는방식 건의드립니다

**Comment by muno9748** [comment]
## 먼저, 이 프로젝에 기여해주셔서 감사합니다!

AppData/Roaming/.minecraft/options.txt의 파일의 key_key.chat 속성을 자동으로 읽어오는 기능을 제안해주셨네요.
좋은 기능으로 생각되어 검토 후 [Pull Request #3](https://github.com/muno9748/HangulPatcher/pull/3)를 업데이트 후
추가를 시도해보겠습니다.

Have a nice day!

Edit. 늦은 답변 죄송합니다.
