### ISSUE TITLE
macOS 지원

### ISSUE THREAD

**Issue by ghost** [muno9748/HangulPatcher#6]
macOS용 파일도 제공해주시면 감사하겠습니다

**Comment by muno9748** [comment]
Electron으로 만들어져 앱 자체는 macOS, Linux 등에서 돌아가게 할수 있지만
Rust로 만들어진 백엔드가 WinAPI를 사용해서
백엔드 구조를 뒤틀어야 하기 때문에 현재로서는 어려울것 같네요

이후 macOS 지원 코드를 추가해보겠습니다. (가능한경우)

피드백 감사합니다.
