### ISSUE TITLE
한가지 제안사항과 한가지 오류

### ISSUE THREAD

**Issue by tjwhang** [muno9748/HangulPatcher#7]
안녕하세요, 1.17에 한글패치 모드가 안나와 개발해보려다가 때려친 개발자입니다. (패브릭은 제 꼰대마인드때매 쓰기 싫고 포지는 개발 환경이 바뀌어서...)
그냥 편해서 이거 쓰고 있는데, 제안사항과 오류 보고 좀 드리려고 합니다. 

제안사항은, 한글 패쳐 프로그램에 간편 설치기를 만들어서 시작프로그램에 등록해놓은뒤, 
jre 경로로 필터링을 해 마인크래프트가 시작될 때를 감지해서 프로그램을 백그라운드에서 실행시키는게 좋을 것 같습니다. 

오류는, 일단 한글 패쳐를 실행시키면 "게임중 한영키 무시"가 활성화되는데, 이는 게임만 영향을 미치는게 아니라 모든 창에 다 영향을 미쳐서 이 글 쓰는데도 영어로 써져 당황했습니다.

위의 제안사항을 수용하시고 코드를 좀만 더 써주시면 아래 오류까지 해결될 듯  하니(하지만 마인크래프트 창 감지는 별도로), 꼭 해주시길 부탁드립니다. 

감사하고, 항상 응원합니다!

**Comment by muno9748** [comment]
안녕하세요 tjwhang님,
바쁘신데 이렇게 긴 글 써주셔서 감사합니다.

LC, 플레인 마인크래프트와 여러 다른 클라이언트의 (특히 LC)
각각 자바 실행파일 경로와 종류가 달라 감지하기 어려운점 양해해주시기 바랍니다.

이런 이유로 키보드 인식을 전역적으로 하고있고,
현재 마인크래프트의 창 감지 기능도 검토중입니다.

현재 1인개발자의 한계와 학업, macOS 지원 관련 이슈로 인해 해당 사항의 업데이트가 지연될수 있습니다.

응원 감사드리고 보다 더 나은 서비스를 제공할수 있도록 노력하겠습니다!
감사합니다

**Comment by muno9748** [comment]
추후 3.0버전에서 윈도우 필터링 적용 예정.
