### ISSUE TITLE
버그

### ISSUE THREAD

**Issue by deadchoco** [muno9748/HangulPatcher#8]
체팅창키를 엔터로 설정하면 프로그램이 잘 작동하지않는 버그가 있는거 같습니다. 해결 가능할까요?

**Comment by ValleyDew** [comment]
그거 저도 그런 버그가 생겼어요

**Comment by ValleyDew** [comment]
그 버그 저도 걸렸어요

**Comment by muno9748** [comment]
코드를 확인해본 결과 엔터키를 채팅창/커맨드 오픈 키로 설정했을때 비정상적인 작동을 하는것으로 확인되었습니다.

더 완벽한 서비스를 만들어갈수 있도록 항상 노력하겠습니다!
감사합니다

**Comment by deadchoco** [comment]
하루빨리 해결되면 좋을 거 같습니다. 감사합니다

**Comment by muno9748** [comment]
3.0.0에서 수정 완료
