### ISSUE TITLE
한글안쳐지는버그

### ISSUE THREAD

**Issue by ValleyDew** [muno9748/HangulPatcher#9]
이거 한글안쳐지는데 어떡해야하나요? 한영키눌렀는데도 안돼요 계속영어만써져요
버그 수정부탁드립니다

**Comment by muno9748** [comment]
안녕하세요 ValletDew님,
현재 제공해주신 정보로는 버그를 찾기 어렵습니다.

추가적인 상황이나 프로그랩 세팅 등등을 올려주시면 더 쉽게 파악할후 있습니다

현재 Issue #8 에서 엔터키를 채팅창/커맨드 오픈키로 설정하면 비정상 작동울 하는것으로 알려졌고 해당 사항에 대해 수정중입니다.

항상 보다 더 나은 서비스를 제공하겠습니다.
감사합니다
